version: 2
jobs:
  build:
    docker:
      - image: library/node:8.4.0-wheezy
    working_directory: ./hibiki
    steps:
      - setup_remote_docker
      - checkout  
      - run:
          name: Resolve Dependencies
          command: npm i --no-optional --save-dev
      - run:
          name: Compile
          command: npm run tsc
notify:
  webhooks:
    - url: https://claraio-circledisc.herokuapp.com/hooks/circleci